Neos:
  Eel:
    defaultContext:
      String: Neos\Eel\Helper\StringHelper
      Array: Neos\Eel\Helper\ArrayHelper
      Date: Neos\Eel\Helper\DateHelper
      Configuration: Neos\Eel\Helper\ConfigurationHelper
      Math: Neos\Eel\Helper\MathHelper
      Json: Neos\Eel\Helper\JsonHelper
      Security: Neos\Eel\Helper\SecurityHelper
      Translation: Neos\Flow\I18n\EelHelper\TranslationHelper
      StaticResource: Neos\Flow\ResourceManagement\EelHelper\StaticResourceHelper
      Type: Neos\Eel\Helper\TypeHelper
      I18n: Neos\Flow\I18n\EelHelper\TranslationHelper
      File: Neos\Eel\Helper\FileHelper
      q: Neos\Eel\FlowQuery\FlowQuery::q
